logging:
#  structured:
#    format:
#      console: logstash
  level:
    liquibase: info
    org.springframework.jdbc: info
    org.springframework.web: debug
    com.broadcom.springconsulting.timeservice: debug
  pattern:
    level: welcome-message:%X{welcome-message} %5p

spring:

  application:
    name: time-service
    org: engineering

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:test-db

#  docker:
#    compose:
#      lifecycle-management: start_only

#  threads:
#    virtual:
#      enabled: true

management:

  endpoints:
    web.exposure.include: '*'

  endpoint:
    env:
      show-values: always
    health:
      show-details: ALWAYS
      group:
        liveness:
          show-details: always
        readiness:
          show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
      org: ${spring.application.org}
      profiles: ${spring.profiles.active}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
          client:
            requests: true

#  prometheus:
#    metrics:
#      export:
#        enabled: false
#        step: 10s

  dynatrace:
    metrics:
      export:
        enabled: true
        v2:
          metric-key-prefix: ${spring.application.name}
          enrich-with-dynatrace-metadata: true
          default-dimensions:
            stack: "homelab-k8s-001"
            region: "dmf-u"

#  wavefront:
#    application:
#      name: ${spring.application.name}
#      service-name: ${spring.application.name}
#      custom-tags:
#        instance_guid: ${CF_INSTANCE_GUID}
#    api-token: 1111-23this-45is-678a-faketoken # this is a fake token since wavefront lib expects a token, though this is not used for authentication to collector for ingestion
#    uri: http://telegraf.hub-collector.service.internal:8765
#    metrics:
#      export:
#        enabled: false

  tracing:
    enabled: true
    sampling:
      probability: 0.5

#  otlp:
#    metrics:
#      export:
#        url: http://otelcol-dm-opentelemetry-collector.monitor.svc.cluster.local:4318/v1/metrics
#    tracing:
#      endpoint: http://otelcol-dm-opentelemetry-collector.monitor.svc.cluster.local:4318/v1/traces

info:
  app:
    version: "@project.version@"

  spring:
    boot:
      version: "@project.parent.version@"